bk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView

urlpatterns = [
    path('singer/', include("singer.urls", namespace="singer")),
    path('admin/', admin.site.urls),
    path(r'', RedirectView.as_view(url='/singer/', permanent=True), name='index')

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

singer/urls.py
from django.urls import include, path
from singer.views import *

app_name = "singer"

urlpatterns = [
    path("start", LoginView.as_view(), name="login"),
    path("", WelcomeView.as_view()),
]

moderator/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.utils import timezone
# Create your models here.


class Genre(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self) -> str:
        return f"{self.title}"


class AttributeKey(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return f"{self.name}"

class Attribute(models.Model):
    key = models.ForeignKey(AttributeKey, on_delete=models.CASCADE)
    value = models.CharField(max_length=255)
    
    def __str__(self) -> str:
        return f"{self.key}: {self.value}"

class Interpret(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name

class Song(models.Model):
    genre = models.ForeignKey(Genre, on_delete=models.DO_NOTHING)
    attributes = models.ManyToManyField(Attribute)
    interpret = models.ForeignKey(Interpret, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.title


class GameDay(models.Model):
    current = models.BooleanField(default=False)
    description = models.TextField(null=True, blank=True)
    genres = models.ManyToManyField(Genre, blank=True)
    #attributes = models.ManyToManyField(Attribute, blank=True)
    created_at = models.DateTimeField(auto_created=True, auto_now_add=True)
    scheduled_at = models.DateTimeField(null=True, blank=True)
    

    def __str__(self):
        if self.current is False:
            if self.scheduled_at is not None:
                if self.scheduled_at > timezone.now():
                    return "Planned at"+self.scheduled_at
                else:
                    return "Ausgelaufen"
            return "Regular Gameday"
        else:
            return "Heutiger GameDay"

play/models.py
from django.db import models

# Create your models here.

singer/models.py
from django.db import models
from moderator.models import Song, GameDay
# Create your models here.

class Singer(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_created=True, auto_now_add=True)
    gameday = models.ForeignKey(GameDay, on_delete=models.CASCADE)
    banned = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class SingerSong(models.Model):
    singer = models.ForeignKey(Singer, on_delete=models.CASCADE)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_created=True, auto_now_add=True)
    accepted = models.BooleanField(default=False)
    planned_order = models.IntegerField()

    def __str__(self):
        return f"{self.song} von {self.singer}"

singer/forms.py
from django import forms
from singer.models import Singer


class SingerLoginForm(forms.ModelForm):


    class Meta:
        model = Singer
        fields = ["name"]

moderator/views.py
from django.shortcuts import render

# Create your views here.

play/views.py
from django.shortcuts import render

# Create your views here.

singer/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.edit import  FormView
from singer.forms import *


# Create your views here.
class WelcomeView(TemplateView):
    template_name = "singer/welcome.html"
    

class LoginView(FormView):
    template_name = "singer/login.html"
    
    form_class = SingerLoginForm

bk/templates/mobile_base.html
{% load static %}

{% block inside_head %}
    <meta charset="utf-8">
    <title>{% block inside_head_title %}{%endblock%}</title>
    <!-- Sets initial viewport load and disables zooming  -->
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- Makes your prototype chrome-less once bookmarked to your phone's home screen -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <!-- Include the compiled Ratchet CSS -->
    <link href="{% static "ratchet/css/ratchet.css" %}" rel="stylesheet">
    <!-- Include the compiled Ratchet JS -->
    <script src="{% static "ratchet/js/ratchet.js" %}"></script>
{% endblock %}
  <body>

    <!-- Make sure all your bars are the first things in your <body> -->
    <header class="bar bar-nav">
      <h1 class="title">{% block page_title %}{% endblock %}</h1>
    </header>

    <!-- Wrap all non-bar HTML in the .content div (this is actually what scrolls) -->
    <div class="content">
      <p class="content-padded">Thanks for downloading Ratchet. This is an example HTML page that's linked up to compiled Ratchet CSS and JS, has the proper meta tags and the HTML structure. Need some more help before you start filling this with your own content? Check out some Ratchet resources:</p>
      <div class="card">
        <ul class="table-view">
          <li class="table-view-cell">
            <a class="push-right" href="http://goratchet.com">
              <strong>Ratchet documentation</strong>
            </a>
          </li>
          <li class="table-view-cell">
            <a class="push-right" href="https://github.com/twbs/ratchet/">
              <strong>Ratchet on Github</strong>
            </a>
          </li>
          <li class="table-view-cell">
            <a class="push-right" href="https://groups.google.com/forum/#!forum/goratchet">
              <strong>Ratchet Google group</strong>
            </a>
          </li>
          <li class="table-view-cell">
            <a class="push-right" href="https://twitter.com/goratchet">
              <strong>Ratchet on Twitter</strong>
            </a>
          </li>
        </ul>
      </div>
    </div>

  </body>
</html>

bk/templates/skeleton.html
<!DOCTYPE html>
<head>
    {% block head_inside %}
    {% endblock }
</head>
<body>
    
</body>
</html>

singer/templates/singer/login.html
{% extends "mobile_base.html" %}
{% load i18n %}
{% load static %}

{% block page_title %}{% trans "Karaoke" %}{% endblock %} 

singer/templates/singer/welcome.html
<!DOCTYPE html>
    <head>
        
    </head>
    <body>
        Willkommen!
        Hier gehts zur Anmeldung!
        <a href="{% url "singer:login" %}">sdfs</a>
    </body>
</html>